### ISSUE TITLE
departure.html.erb の変数

### ISSUE THREAD

**Issue by HayatoMatsumuro** [HayatoMatsumuro/notopochi#11]
url_depart ： depart のURL
user_name ： ログインしているユーザー名
list_from : from のリスト {optionvalue, fromの名前} 形式の2次元配列
list_to : toのリスト {optionvalue, fromの名前} 形式の2次元配列

**Comment by higaa** [comment]
@userName: ログインしているユーザー名
@departurePoints: 出発地の配列
で設定しようと思います。

**Comment by higaa** [comment]
訂正
@userName: ログインしているユーザー名
@departurePoints: 出発地のIDと名前のハッシュの配列
    例: @departurePoints = [ { :id => "1", :name => "金沢駅(ダミーデータ)" },
            { :id => "2", :name => "香林坊(ダミーデータ)" } ]
で設定しようと思います。
