### ISSUE TITLE
Webブラウザ 現在値を取得する方法

### ISSUE THREAD

**Issue by HayatoMatsumuro** [HayatoMatsumuro/notopochi#12]
表題の通り

**Comment by higaa** [comment]
Geolocation API を使えばいいと思う。
http://www.htmq.com/geolocation/

**Comment by HayatoMatsumuro** [comment]
できました。
Geolocation API を使いました。
ボタン押したとき、位置情報取得を開始して、取得できてからform 送信します。
ですので、ボタン押しから送信まで若干タイムラグがあります。

**Comment by HayatoMatsumuro** [comment]
arrive 時も同処理を追加しましょう！
