### ISSUE TITLE
arrived.html.erb の変数

### ISSUE THREAD

**Issue by HayatoMatsumuro** [HayatoMatsumuro/notopochi#20]

**Comment by KawaguchiDaisuke** [comment]
到着画面に以下の情報を表示させるつもりです
username: ユーザー名
times: 時間
points: GPS情報

notopochi_controllerに暫定値を入れましたが、
変数名、型は変えていただいても大丈夫です。

**Comment by KawaguchiDaisuke** [comment]
引数で以下の情報を追加しました。
names: 到着した場所
comments: 到着した場所のコメント
